# Generated by Django 5.0.6 on 2024-06-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NewsPortal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moreuserinfo",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
