# Generated by Django 5.0.6 on 2024-06-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NewsPortal", "0002_alter_moreuserinfo_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="moreuserinfo",
            name="is_completed_forlawyer",
            field=models.BooleanField(default=False),
        ),
    ]
