# Generated by Django 5.0.6 on 2024-06-18 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NewsPortal", "0003_moreuserinfo_is_completed_forlawyer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moreuserinfo",
            old_name="is_completed_forlawyer",
            new_name="is_completed_for_lawyer",
        ),
    ]
