# Generated by Django 5.0.6 on 2024-06-22 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "NewsPortal",
            "0004_rename_is_completed_forlawyer_moreuserinfo_is_completed_for_lawyer",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moreuserinfo",
            name="is_completed_for_lawyer",
        ),
    ]
