# Generated by Django 5.0.6 on 2024-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("NewsPortal", "0005_remove_moreuserinfo_is_completed_for_lawyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="moreuserinfo",
            name="is_completed_for_lawyer",
            field=models.BooleanField(default=False),
        ),
    ]
