# Generated by Django 5.0.6 on 2024-06-23 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("NewsPortal", "0006_moreuserinfo_is_completed_for_lawyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moreuserinfo",
            name="is_completed_for_lawyer",
        ),
    ]
