# Generated by Django 5.0.6 on 2024-06-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LawyerRecommendation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyerdetails",
            name="Rating",
            field=models.IntegerField(default=0),
        ),
    ]
