# Generated by Django 5.0.7 on 2024-08-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LawyerRecommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyerdataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('average_case_completion_days', models.IntegerField()),
                ('bar_license', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('province', models.CharField(max_length=255)),
            ],
        ),
    ]
