# Generated by Django 5.0.7 on 2024-08-21 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LawyerRecommendation", "0002_lawyerdataset"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="lawyerdataset",
            table="lawyerrecommendation_lawyerdataset",
        ),
    ]
