# Generated by Django 5.0.6 on 2024-06-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LawyerRecommendation", "0002_lawyerdetails_is_lawyer_lawyerdetails_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyerdetails",
            name="permanent_address",
            field=models.CharField(max_length=255),
        ),
    ]
