# Generated by Django 5.0.7 on 2024-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LawyerRecommendation", "0004_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
