# Generated by Django 5.0.7 on 2024-08-20 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("LawyerRecommendation", "0005_fileupload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FileUpload",
        ),
    ]
