# Generated by Django 5.0.7 on 2024-08-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LawyerRecommendation", "0005_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="meeting_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
